
services:
  sonarr:
    extends:
      file: ./compose.features.yml
      service: "${COMPOSE_VARIANT:-default}"
    # https://hub.docker.com/r/linuxserver/sonarr
    image: linuxserver/sonarr:latest
    container_name: sonarr
    #network_mode: "host"
    ports:
      - "${HTTP_BIND_ADDR:-127.0.0.1}:${HTTP_BIND_PORT:-8989}:8989/tcp"
    env_file: .env
    volumes:
      - "${CONFIG_PATH}:/config"
      # Using same path to fix integration with transmission working on host
      - "${TVSERIES_PATH}:${TVSERIES_PATH}"
      #- "${TVSERIES_PATH}:/tv"
      #- "${DOWNLOADS_PATH}:/downloads"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"

networks:
  traefik:
    external: true
    name: "${TRAEFIK_NETWORK:-traefik}"
