# https://gitlab.com/Deamos/flask-nginx-rtmp-manager/-/blob/master/docker-compose.yml
version: '3.7'

services:
  redis:
    image: redis
    container_name: ospredis
    expose:
      - 6379
  app:
    image: deamos/openstreamingplatform
    ports:
      - "1935:1935/tcp"
      - "127.0.0.1:8585:80/tcp"
      - "127.0.0.1:8553:443/tcp"
    environment:
      - REDIS_HOST=ospredis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
    env_file: .env
    volumes:
      - "${STORAGE_DIR}:/var/www"
      - "${DATABASE_DIR}:/opt/osp/db"
      - "${NGINX_DIR}:/usr/local/nginx/conf"
    depends_on:
      - redis
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"
