# https://hub.docker.com/r/jaymoulin/jdownloader
version: '3.7'

services:
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    user: "${HOST_USER}:${HOST_GROUP}"
    volumes:
      - "${CONFIG_PATH:-./config/config}:/opt/JDownloader/app/cfg"
      - "${DOWNLOADS_PATH:-./data}:/opt/JDownloader/Downloads"
      - "${LOGS_PATH:-./config/logs}:/opt/JDownloader/app/logs" #optional
      - /etc/localtime:/etc/localtime:ro #optional
    env_file: ".env"
    #environment:
      #MYJD_USER: email@email.com #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      #MYJD_PASSWORD: bar #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      #MYJD_DEVICE_NAME: "${MYJD_DEVICE_NAME}" #optional
      #XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads #optional
    ports:
      - "${MYJD_BIND_PORT:-3129}:3129"
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"