services:
  default: {}

  traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: "${TRAEFIK_NETWORK:-traefik}"
      traefik.http.routers.sish.rule: "HostRegexp(`${TRAEFIK_HOST_REGEXP}`)"
      traefik.http.routers.sish.entrypoints: "${TRAEFIK_ENTRYPOINT:-websecure}"
      traefik.http.services.sish.loadbalancer.server.port: "${TRAEFIK_SERVICE_PORT:-8395}"
