version: '3.7'

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - gitea
    ports:
      - "${EXT_HTTP_PORT:-3000}:3000"
      - "${EXT_SSH_PORT:-222}:22"
    volumes:
      - "${HOST_DATA_DIR:-./data}:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - "${HOST_PG_DATA_DIR:-./db}:/var/lib/postgresql/data"