version: '3.7'

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    network_mode: host
    ports:
      - "${HTTP_BIND_ADDR:-127.0.0.1}:${EXT_HTTP_PORT:-3000}:3000"
      - "${EXT_SSH_PORT:-222}:22"
    volumes:
      - "${HOST_DATA_DIR:-./data}:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - "GITEA__database__HOST=${DB_HOST:-db}:${DB_PORT:-5432}"
      - "GITEA__database__NAME=${DB_NAME:-gitea}"
      - "GITEA__database__USER=${DB_USER:-gitea}"
      - "GITEA__database__PASSWD=${DB_PASSWD:-gitea}"
