services:
  livekit_default: {}

  livekit_traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: "${TRAEFIK_NETWORK:-traefik}"
      traefik.http.routers.matrix-calls-livekit.rule: "Host(`${TRAEFIK_HOST}`)"
      traefik.http.routers.matrix-calls-livekit.entrypoints: "${TRAEFIK_ENTRYPOINT:-websecure}"
      traefik.http.routers.matrix-calls-livekit.middlewares: "${TRAEFIK_ACCESS_POLICY:-default-access@file}"
      traefik.http.routers.matrix-calls-livekit.service: "matrix-calls-livekit"
      traefik.http.services.matrix-calls-livekit.loadbalancer.server.port: "7880"

  jwt_default: {}

  jwt_traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: "${TRAEFIK_NETWORK:-traefik}"
      traefik.http.routers.matrix-calls-jwt.rule: >-
        Host(`${TRAEFIK_HOST}`) &&
        (PathPrefix(`/sfu/get`) || PathPrefix(`/healthz`) || PathPrefix(`/get_token`))
      traefik.http.routers.matrix-calls-jwt.priority: "100"
      traefik.http.routers.matrix-calls-jwt.entrypoints: "${TRAEFIK_ENTRYPOINT:-websecure}"
      traefik.http.routers.matrix-calls-jwt.middlewares: "${TRAEFIK_ACCESS_POLICY:-default-access@file}"
      traefik.http.routers.matrix-calls-jwt.service: "matrix-calls-jwt"
      traefik.http.services.matrix-calls-jwt.loadbalancer.server.port: "8411"
