services:
  default: {}

  traefik:
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: "${TRAEFIK_NETWORK:-traefik}"
      traefik.http.routers.forgejo.rule: "Host(`${TRAEFIK_HOST}`)"
      traefik.http.routers.forgejo.entrypoints: "${TRAEFIK_ENTRYPOINT:-websecure}"
      traefik.http.services.forgejo.loadbalancer.server.port: "${TRAEFIK_SERVICE_PORT:-3000}"
