version: '3.7'

services:
  nextcloud:
    # https://hub.docker.com/r/linuxserver/nextcloud
    image: linuxserver/nextcloud
    container_name: nextcloud
    #network_mode: "host"
    ports:
      - "${EXT_PORT}:443/tcp"
    env_file: .env
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${DATA_PATH}:/data"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"
