services:
  default: {}

  traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.http.routers.radarr.rule: 'Host(`${TRAEFIK_HOST}`)'
      traefik.http.routers.radarr.entrypoints: '${TRAEFIK_ENTRYPOINT:-websecure}'
      traefik.http.services.radarr.loadbalancer.server.port: '${TRAEFIK_SERVICE_PORT:-7878}'
