services:
  default: {}

  traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.http.routers.folding-at-home.rule: 'Host(`${TRAEFIK_HOST}`)'
      traefik.http.routers.folding-at-home.entrypoints: '${TRAEFIK_ENTRYPOINT:-websecure}'
      traefik.http.services.folding-at-home.loadbalancer.server.port: '${TRAEFIK_SERVICE_PORT:-7396}'
