services:
  tor-privoxy:
    # https://hub.docker.com/r/dperson/torproxy
    # Temporary using my own image with obfs4 support until it hits upstream
    image: registry.gitlab.com/skobkin/torproxy-obfs4
    container_name: tor-privoxy
    ports:
      - "${TOR_HOST_ADDR:-127.0.0.1}:${TOR_HOST_HTTP_PORT:-8118}:8118/tcp"
      - "${TOR_HOST_ADDR:-127.0.0.1}:${TOR_HOST_SOCKS_PORT:-9050}:9050/tcp"
      - "${TOR_HOST_ADDR:-127.0.0.1}:${TOR_HOST_TRANS_PORT:-9040}:9040/tcp"
      - "${TOR_HOST_ADDR:-127.0.0.1}:${TOR_HOST_DNS_PORT:-5353}:5353/tcp"
    extra_hosts:
      # You can use host.docker.internal to use proxy from the host to connect to Tor
      - "host.docker.internal:host-gateway"
    volumes:
      - "./config/torrc:/etc/tor/torrc:ro"
    env_file: .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"
