# https://github.com/tarampampam/webhook-tester

services:
  webhook-tester:
    extends:
      file: ./compose.features.yml
      service: "${COMPOSE_VARIANT:-default}"
    image: "ghcr.io/tarampampam/webhook-tester:2.3.0"
    container_name: "webhook-tester"
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - "${BIND_ADDR:-127.0.0.1}:${BIND_PORT:-8414}:8080/tcp"
    environment:
      STORAGE_DRIVER: "fs"
      FS_STORAGE_DIR: "/data"
    env_file: .env
    volumes:
      - "${HOST_DATA_DIR:-./data}:/data"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"

networks:
  traefik:
    external: true
    name: "${TRAEFIK_NETWORK:-traefik}"
