# https://hub.docker.com/r/superseriousbusiness/gotosocial

services:
  gotosocial:
    image: "superseriousbusiness/gotosocial:${IMAGE_VERSION:-latest}"
    container_name: gotosocial
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - gotosocial
    env_file:
      - .env
    environment:
      # Essential GoToSocial configuration
      GTS_CONFIG_PATH: "/gotosocial/config.yaml"
      GTS_TRUSTED_PROXIES: "${NETWORK_GATEWAY:-172.30.0.1}"
      GTS_WAZERO_COMPILATION_CACHE: "/gotosocial/.cache"
    ports:
      # For reverse proxy setups
      - "${BIND_ADDR:-127.0.0.1}:${BIND_PORT:-8080}:8080"
    volumes:
      # Data volume for sqlite.db and media files
      - "${DATA_PATH:-./data}:/gotosocial/storage"
      # Wazero compilation cache
      - "${CACHE_PATH:-./cache}:/gotosocial/.cache"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"

networks:
  gotosocial:
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_SUBNET:-172.30.0.0/16}"
          gateway: "${NETWORK_GATEWAY:-172.30.0.1}"
