services:
  default: {}

  traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.docker.network: '${TRAEFIK_NETWORK:-traefik}'
      traefik.http.routers.phanpy.rule: 'Host(`${TRAEFIK_HOST}`)'
      traefik.http.routers.phanpy.entrypoints: '${TRAEFIK_ENTRYPOINT:-websecure}'
      traefik.http.services.phanpy.loadbalancer.server.port: '${TRAEFIK_SERVICE_PORT:-80}'
