# https://git.skobk.in/skobkin/phanpy-docker

services:
  phanpy:
    extends:
      file: ./compose.features.yml
      service: "${COMPOSE_VARIANT:-default}"
    image: '${IMAGE_REPOSITORY:-ghcr.io/skobkin/phanpy-docker}:${IMAGE_TAG:-latest}'
    container_name: 'phanpy'
    hostname: 'phanpy'
    ports:
      - '${BIND_ADDRESS:-127.0.0.1}:${BIND_PORT:-8403}:80'
    env_file: '.env'
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE:-5m}'
        max-file: '${LOG_MAX_FILE:-5}'

networks:
  traefik:
    external: true
    name: '${TRAEFIK_NETWORK:-traefik}'
