services:
  default:
    extends:
      file: 'gpu-support.yml'
      service: '${GPU_DRIVER:-rocm}'

  traefik:
    extends:
      file: 'gpu-support.yml'
      service: '${GPU_DRIVER:-rocm}'
    networks:
      - default
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.http.routers.invokeai.rule: 'Host(`${TRAEFIK_HOST}`)'
      traefik.http.routers.invokeai.entrypoints: '${TRAEFIK_ENTRYPOINT:-websecure}'
      traefik.http.routers.invokeai.middlewares: "${TRAEFIK_ACCESS_POLICY:-default-access@file}"
      traefik.http.services.invokeai.loadbalancer.server.port: '${TRAEFIK_SERVICE_PORT:-9090}'
