version: '3.7'

services:
  portainer:
    # https://hub.docker.com/r/portainer/portainer
    image: portainer/portainer
    container_name: portainer
    ports:
      - "127.0.0.1:9000:9000/tcp"
      #- "127.0.0.1:8000:8000/tcp"
    volumes:
      # Persistent data volume
      - "${DATA_PATH:-portainer_data}:/data"
      # Docker socket
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"

volumes:
  portainer_data:
    name: portainer_data
