# https://hub.docker.com/r/vectorim/element-web

services:
  element-web:
    extends:
      file: ./compose.features.yml
      service: "${COMPOSE_VARIANT:-default}"
    image: 'vectorim/element-web:${IMAGE_TAG:-latest}'
    container_name: element-web
    volumes:
      - "./config/config.json:/app/config.json"
    ports:
      - "${WEBUI_BIND_ADDR}:${WEBUI_BIND_PORT}:80"
    env_file: .env
    restart: unless-stopped
    user: "${HOST_USER:-0}"
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"

networks:
  traefik:
    external: true
    name: "${TRAEFIK_NETWORK:-traefik}"
