services:
  ollama:
    extends:
      file: ./compose.features.yml
      service: "${COMPOSE_VARIANT:-default}"
    image: 'ollama/ollama:${OLLAMA_IMAGE_TAG:-latest}'
    container_name: ollama
    #user: "${HOST_USER:-1000}"
    volumes:
      - '${HOST_OLLAMA_DATA_DIR:-./data}:/root/.ollama'
    ports:
      - '${HTTP_OLLAMA_BIND_ADDR:-127.0.0.1}:${HTTP_OLLAMA_BIND_PORT:-11434}:11434/tcp'
    devices:
      - '${DEV_DRI:-/dev/dri}:${DEV_DRI:-/dev/dri}'
      - '${DEV_KFD:-/dev/kfd}:${DEV_KFD:-/dev/kfd}'
    env_file: .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '${LOG_MAX_SIZE:-5m}'
        max-file: '${LOG_MAX_FILE:-5}'

networks:
  ai-tools:
    external: true
  proxy:
    external: true
    name: "${PROXY_NETWORK:-proxy}"
