version: '3.9'

services:
  webui:
    image: 'ghcr.io/open-webui/open-webui:${UI_IMAGE_TAG:-main}'
    container_name: ollama-open-webui
    volumes:
      - '${HOST_UI_DATA_DIR:-./data/open-webui}:/app/backend/data'
    depends_on:
      - ollama
    ports:
      - '${HTTP_UI_BIND_ADDR:-127.0.0.1}:${HTTP_UI_BIND_PORT-3000}:8080'
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${UI_SECRET_KEY:-changeme}'
      # STT (Whisper):
      # https://docs.openwebui.com/getting-started/env-configuration/#speech-to-text-openai
      - 'AUDIO_STT_ENGINE=${AUDIO_STT_ENGINE:-}'
      - 'AUDIO_STT_OPENAI_API_BASE_URL=${AUDIO_STT_OPENAI_API_BASE_URL:-}'
    #extra_hosts:
    #  - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ai-tools
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE:-5m}'
        max-file: '${LOG_MAX_FILE:-5}'

  ollama:
    image: 'ollama/ollama:${OLLAMA_IMAGE_TAG:-latest}'
    container_name: ollama
    #user: "${HOST_USER:-1000}"
    volumes:
      - '${HOST_OLLAMA_DATA_DIR:-./data}:/root/.ollama'
    ports:
      - '${HTTP_OLLAMA_BIND_ADDR:-127.0.0.1}:${HTTP_OLLAMA_BIND_PORT:-11434}:11434/tcp'
    devices:
      - '${DEV_DRI:-/dev/dri}:${DEV_DRI:-/dev/dri}'
      - '${DEV_KFD:-/dev/kfd}:${DEV_KFD:-/dev/kfd}'
    env_file: .env
    restart: unless-stopped
    networks:
      - ai-tools
    logging:
      driver: "json-file"
      options:
        max-size: '${LOG_MAX_SIZE:-5m}'
        max-file: '${LOG_MAX_FILE:-5}'

networks:
  ai-tools:
    external: true
