services:
  default: {}

  traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.docker.network: '${TRAEFIK_NETWORK:-traefik}'
      traefik.http.routers.frigate.rule: 'Host(`${TRAEFIK_HOST:-frigate.example.com}`)'
      traefik.http.routers.frigate.entrypoints: '${TRAEFIK_ENTRYPOINT:-websecure}'
      traefik.http.routers.frigate.middlewares: 'chain-default@file'
      traefik.http.services.frigate.loadbalancer.server.port: '8971'
