services:
  default: {}

  traefik:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.http.routers.syncthing.rule: 'Host(`${TRAEFIK_HOST}`)'
      traefik.http.routers.syncthing.entrypoints: '${TRAEFIK_ENTRYPOINT:-websecure}'
      traefik.http.services.syncthing.loadbalancer.server.port: '${TRAEFIK_SERVICE_PORT:-8384}'
