# https://github.com/frdel/agent-zero
# https://hub.docker.com/r/frdel/agent-zero-run

services:
  agent-zero:
    image: 'frdel/agent-zero-run:${IMAGE_TAG:-latest}'
    container_name: agent-zero
    volumes:
      - '${HOST_DATA_DIR:-./data}:/a0'
    ports:
      - '${HTTP_BIND_ADDR:-127.0.0.1}:${HTTP_BIND_PORT:-8396}:80'
    environment:
      - 'TZ=${TZ:-Europe/Moscow}'
    env_file: .env
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE:-5m}'
        max-file: '${LOG_MAX_FILE:-5}'
    networks:
      - ai-tools

networks:
  ai-tools:
    external: true
