when:
  event:
    - pull_request
    - push
  branch:
    - master

steps:
  - name: check-policy
    image: alpine/git:2.49.1
    commands:
      - sh .woodpecker/scripts/check-policy.sh

  - name: validate-compose
    image: dockette/docker:latest
    commands:
      - sh .woodpecker/scripts/validate-compose.sh
