version: '3.7'

services:
  wireguard:
    # https://hub.docker.com/r/cmulk/wireguard-docker
    image: cmulk/wireguard-docker:alpine
    container_name: wireguard
    volumes:
      - "${CONFIG_DIR:-./config}:/etc/wireguard:ro"
    networks:
      - network
    ports:
    - "${PORT:-5555}:5555/udp"
    env_file: .env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"

networks:
  network:
