version: '3.7'

services:
  mtg:
    image: nineseconds/mtg:stable
    container_name: proxy-mtproto
    ports:
      - "${MTG_IPV4_PORT}:${MTG_PORT}/tcp"
    env_file: .env
    restart: unless-stopped
    command: "/mtg ${MTPROTO_SECRET:-} ${MTPROTO_TAG:-}"
