version: '3.7'

services:
  mtg:
    image: nineseconds/mtg:stable
    container_name: proxy-mtproto
    ports:
      - "444:443/tcp"
    env_file: .env
    restart: unless-stopped
    command: "${MTPROTO_SECRET} ${MTPROTO_TAG}"
