version: '3.7'

services:
  mtg:
    image: nineseconds/mtg:latest
    container_name: proxy-mtproto
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}/tcp"
    env_file: .env
    restart: unless-stopped
    command: "run ${PROXY_SECRET} ${PROXY_TAG}"
