services:
  default: {}

  traefik:
    networks:
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.docker.network: '${TRAEFIK_NETWORK:-traefik}'

      traefik.http.routers.booklore.rule: 'Host(`${TRAEFIK_HOST}`)'
      traefik.http.routers.booklore.entrypoints: '${TRAEFIK_ENTRYPOINT:-websecure}'
      traefik.http.routers.booklore.middlewares: "${TRAEFIK_ACCESS_POLICY:-default-access@file}"
      traefik.http.routers.booklore.service: booklore

      # Shared service definition
      traefik.http.services.booklore.loadbalancer.server.port: '${TRAEFIK_SERVICE_PORT:-6060}'
